name: Build and Test Docker

on: 
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:
  merge_group:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: SageSeekerSociety/cheese-auth

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: server
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

      - name: Create env file
        run: cp sample.env .env

      - name: set cheese-auth image tag
        run: echo "CHEESE_AUTH_TAG=${{ steps.meta.outputs.version }}" >> "$GITHUB_ENV"

      - name: Start compose
        run: |
          docker compose --file docker-compose.yml up --no-build --detach

          # Check the health of all services, wait for them to become healthy
          max_tries=10
          tries=0
          until [ $(docker compose ps | grep -c 'healthy') -eq \
              $(docker compose ps -q | wc -l) ] || [ $tries -eq $max_tries ]; do
            echo "Waiting for all services to become healthy... (try $((tries+1))/$max_tries)"
            sleep 5
            tries=$((tries+1))
          done

          if [ $tries -eq $max_tries ]; then
            echo "Services did not become healthy after $max_tries tries."
            docker compose ps
            docker compose logs cheese-auth
            exit 1
          fi

      # See: https://remarkablemark.org/blog/2022/05/12/github-actions-postgresql-increase-max-connections-and-shared-buffers/
      # See: https://stackoverflow.com/questions/70673766/how-to-increase-max-connection-in-github-action-postgres
      - name: Increase PostgreSQL max_connections
        run: |
          docker exec -i cheese-auth-database-1 bash << EOF
            sed -i -e 's/max_connections = 100/max_connections = 1000/' /var/lib/postgresql/data/postgresql.conf
            sed -i -e 's/shared_buffers = 128MB/shared_buffers = 2GB/' /var/lib/postgresql/data/postgresql.conf
          EOF
          docker restart --time 0 cheese-auth-database-1

      - name: Run Test
        run: docker compose exec cheese-auth pnpm run test:cov
